@startuml Modulos

package "VoxCan" {
    
    package "Integración de Sensores" as IS {
        [Sensores de Distancia por Ultrasonidos]
    }
    
    package "Gestión de Energía" as GE {
        [Pilas]
        [Powerbank]
    }
    
    package "Integración de Placas Base" as IPB {

        package "Lógica" as LC {
            [Placa Base Raspberry Pi]
            [Módulo de Interacción por Voz]
            [Módulo de Movimiento]
        }

        package "Mecanica" as MC {
            [Placa Base Arduino]

            package "Control de Movimiento" as CM {
                [Controlador de Servomotores]
            }
        }
        
        package "Control de LEDs" as CLA {
            [Control de LEDs]
        }

        package "Interfaz de Usuario y Control de Voz" as IU {
            [WebServer]
            [Web HTML]
        }

        package "Procesamiento de Audio y Reconocimiento de Voz" as PARV {
            [Algoritmos de Procesamiento de Señales de Audio]
        }

        package "Procesamiento de la cinemática de movimiento" as PMV {
            [Algoritmos de Movimiento y Cinemática]
        }
    }

    [Web HTML] <--> [WebServer]
    [WebServer] <--> [Placa Base Raspberry Pi]

    [Placa Base Raspberry Pi] --> [Módulo de Interacción por Voz]
    [Placa Base Raspberry Pi] --> [Módulo de Movimiento]
    [Placa Base Raspberry Pi] --> [Control de LEDs]
    
    [Placa Base Arduino] --> [Controlador de Servomotores] 
    
    [Módulo de Movimiento] <--> [Algoritmos de Movimiento y Cinemática]
    [Módulo de Interacción por Voz] <--> [Algoritmos de Procesamiento de Señales de Audio]
        
    [Algoritmos de Movimiento y Cinemática] --> [Placa Base Arduino]
    [Sensores de Distancia por Ultrasonidos] --> [Módulo de Movimiento]
    
    [Pilas] --> [Controlador de Servomotores]
    [Powerbank] --> [Placa Base Raspberry Pi]
}

@enduml